name: verificacion rapida

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checar r
        uses: actions/checkout@v4epositorio

      - name: Verificar que todo funcione
        run: echo "Todo funciona correctamente"
